# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aeeb5a0125694f9a00b74968e3d69b66"
name = "Epic Fulfill: Bulk Orders"
handle = "epic-fulfill-bulk-orders"
application_url = "https://gravity-bucks-rhythm-bag.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_assigned_fulfillment_orders,write_customers,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_third_party_fulfillment_orders,read_locations"

[auth]
redirect_urls = [
  "https://gravity-bucks-rhythm-bag.trycloudflare.com/auth/callback",
  "https://gravity-bucks-rhythm-bag.trycloudflare.com/auth/shopify/callback",
  "https://gravity-bucks-rhythm-bag.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
